function mre=gsvd_vs_gevd(g11)
disp(sprintf('test with G(1,1)=%.15e',g11));
F=[1 1 1 1; 0 1 1 1; 0 0 1 1; 0 0 0 1];
disp(sprintf('matrix F, cond(F)=%.15e',cond(F)));
disp(sprintf(' %.15e',F(1,:)));
disp(sprintf(' %.15e',F(2,:)));
disp(sprintf(' %.15e',F(3,:)));
disp(sprintf(' %.15e',F(4,:)));
G=F;
G(1,1)=g11;
disp(sprintf('matrix G, cond(G)=%.15e',cond(G)));
disp(sprintf(' %.15e',G(1,:)));
disp(sprintf(' %.15e',G(2,:)));
disp(sprintf(' %.15e',G(3,:)));
disp(sprintf(' %.15e',G(4,:)));
A=F'*F;
disp(sprintf('matrix A=F''*F, cond(A)=%.15e',cond(A)));
disp(sprintf(' %.15e',A(1,:)));
disp(sprintf(' %.15e',A(2,:)));
disp(sprintf(' %.15e',A(3,:)));
disp(sprintf(' %.15e',A(4,:)));
B=G'*G;
disp(sprintf('matrix B=G''*G, cond(B)=%.15e',cond(B)));
disp(sprintf(' %.15e',B(1,:)));
disp(sprintf(' %.15e',B(2,:)));
disp(sprintf(' %.15e',B(3,:)));
disp(sprintf(' %.15e',B(4,:)));
S=gsvd(F,G);
disp('gsvd(F,G)');
disp(sprintf(' %.15e',S));
S2=S.^2;
disp('generalized eigenvalues as squared generalized singular values');
disp(sprintf(' %.15e',S2));
E=eig(A,B);
disp('eig(A,B)');
disp(sprintf(' %.15e',E));
AE=abs(S2-E);
disp('error |S^2-E|');
disp(sprintf(' %.15e',AE));
RE=AE./S2;
disp('relative error |S^2-E|/S^2');
disp(sprintf(' %.15e',RE));
mre=max(RE);
end
